#!/bin/bash
# Alacritty-Kitty one-line installer
set -euo pipefail

BIN_DIR="${HOME}/.local/bin"
CONF_DIR="${HOME}/.config/alacritty"
SYSTEMD_DIR="${HOME}/.config/systemd/user"
APPS_DIR="${HOME}/.local/share/applications"
EXE="${BIN_DIR}/alacritty"

green() { echo -e "\033[32m$*\033[0m"; }
red()   { echo -e "\033[31m$*\033[0m"; }

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║  Alacritty-Kitty  —  installer      ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# ---- Build ----
if [ -f "./target/release/alacritty" ]; then
  green "[1/5] Binary already built (skipping cargo build --release)"
else
  echo "[1/5] Building release binary..."
  cargo build --release
  green "  ✓ Build done"
fi

# ---- Install binary ----
echo "[2/5] Installing binary to ${BIN_DIR}"
mkdir -p "${BIN_DIR}"
# Unlink first to handle "Text file busy" if alacritty is running
rm -f "${EXE}"
cp ./target/release/alacritty "${EXE}" 2>/dev/null || {
  red "  ✗ Cannot write to ${EXE} — close all alacritty instances first"
  exit 1
}
chmod +x "${EXE}"
green "  ✓ ${EXE}"

# ---- Config ----
echo "[3/5] Installing default config"
mkdir -p "${CONF_DIR}"
if [ ! -f "${CONF_DIR}/alacritty.toml" ]; then
  # Generate only if not present
  cat > "${CONF_DIR}/alacritty.toml" << 'TOML'
# Alacritty-Kitty Configuration
# Generated by install.sh — customize freely.

[general]
live_config_reload = true
ipc_socket = true

[env]
TERM = "alacritty"

[window]
startup_mode = "Fullscreen"
decorations = "None"
option_as_alt = "None"

[font]
size = 11

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }

[tabs]
tab_bar_edge = "top"
tab_bar_style = "Slant"
tab_bar_min_tabs = 1

[tabs.mouse]
enabled = true

[menu]
menu_bar_edge = "bottom"

[[menu.items]]
label = "PAN"
[[menu.items.submenu]]
label = "SPLIT"
[[menu.items.submenu.submenu]]
label = "RIGHT"
action = "split-right"
[[menu.items.submenu.submenu]]
label = "DOWN"
action = "split-down"
[[menu.items.submenu]]
label = "RESIZE"
action = "resize-mode"
[[menu.items.submenu]]
label = "KILL"
action = "close-pane"
[[menu.items.submenu]]
label = "FULL"
action = "toggle-zoom"

[[menu.items]]
label = "TAB"
[[menu.items.submenu]]
label = "CREATE"
action = "create-tab"
[[menu.items.submenu]]
label = "KILL"
action = "close-tab"
[[menu.items.submenu]]
label = "RENAME"
action = "rename-tab"
[[menu.items.submenu]]
label = "PIN"
action = "pin-tab"

[[menu.items]]
label = "SESS"
[[menu.items.submenu]]
label = "SAVE"
action = "save-session"
[[menu.items.submenu]]
label = "LOAD"
list = "sessions"
TOML
  green "  ✓ ${CONF_DIR}/alacritty.toml"
else
  green "  ✓ Config exists, skipping"
fi

# ---- Systemd unit ----
echo "[4/5] Installing systemd user unit"
mkdir -p "${SYSTEMD_DIR}"
cat > "${SYSTEMD_DIR}/alacritty-ipc.service" << UNIT
[Unit]
Description=Alacritty-Kitty IPC daemon
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=${EXE} --daemon
Restart=no

[Install]
WantedBy=graphical-session.target
UNIT
systemctl --user daemon-reload 2>/dev/null || true
green "  ✓ ${SYSTEMD_DIR}/alacritty-ipc.service"

# ---- Desktop entry ----
echo "[5/5] Installing desktop entry"
mkdir -p "${APPS_DIR}"
cat > "${APPS_DIR}/alacritty.desktop" << DESKTOP
[Desktop Entry]
Type=Application
Name=Alacritty-Kitty
Comment=GPU terminal with tabs, tiling, modal menu
Icon=utilities-terminal
Exec=${EXE}
Terminal=false
Categories=System;TerminalEmulator;
StartupNotify=true
StartupWMClass=Alacritty
Actions=NewWindow;

[Desktop Action NewWindow]
Name=New Window
Exec=${EXE} msg create-window
DESKTOP
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "${APPS_DIR}" 2>/dev/null || true
green "  ✓ ${APPS_DIR}/alacritty.desktop"

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║  Install complete!                   ║"
echo "  ║                                      ║"
echo "  ║  Run:  alacritty                     ║"
echo "  ║  Daemon: systemctl --user start      ║"
echo "  ║          alacritty-ipc               ║"
echo "  ╚══════════════════════════════════════╝"
echo ""
